import React from 'react';
import Link from 'next/link';
import { Terminal, Shield, Zap, ArrowRight } from 'lucide-react';

export default function AboutPage() {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 space-y-8 font-mono">
      <div className="space-y-3">
        <span className="text-[10px] font-mono text-[#f59e0b] uppercase tracking-wider block">
          ABOUT SIGNALFORGE
        </span>
        <h1 className="text-3xl font-extrabold text-slate-100">
          Engineering Signal Over Noise
        </h1>
        <p className="text-xs sm:text-sm text-zinc-400 font-sans leading-relaxed">
          SignalForge is built on a simple premise: genuine authority in software engineering cannot be faked with generic AI templates or breathless LinkedIn engagement bait.
        </p>
      </div>

      <div className="p-6 rounded-xl bg-[#0e1710] border border-[#22c55e]/30 space-y-4">
        <h2 className="text-sm font-bold text-emerald-400 uppercase tracking-wider">
          The 4 Pillars of SignalForge
        </h2>
        <div className="space-y-3 text-xs text-zinc-300 font-sans leading-relaxed">
          <p>
            <strong>1. Real-Time Radar:</strong> We monitor technical papers, system blogs, and kernel mailing lists to detect shifts in distributed systems and AI inference before they become commoditized.
          </p>
          <p>
            <strong>2. Anti-Spam Engagement:</strong> We refuse mass-commenting bots. Every suggested comment generated by SignalForge is designed to add genuine mathematical or operational perspective.
          </p>
          <p>
            <strong>3. STAR Grounding:</strong> Content is grounded in the user&apos;s verified experience vault—ensuring every publication reflects real production incidents and architectural trade-offs.
          </p>
          <p>
            <strong>4. Career Signal Alignment:</strong> Direct alignment with Staff and Principal job specifications at high-bar infrastructure organizations.
          </p>
        </div>
      </div>

      <div className="pt-4">
        <Link
          href="/dashboard"
          className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg bg-[#22c55e] text-black font-bold text-xs hover:bg-emerald-400 transition"
        >
          <span>Open Console Hub</span>
          <ArrowRight className="w-4 h-4" />
        </Link>
      </div>
    </div>
  );
}
